source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'json'
gem 'bson'
gem 'bson_ext'
gem 'logger'
gem 'pony'
gem 'foreman'
gem 'data_mapper'
gem 'puma'

group :development do
  gem 'shotgun'
  gem 'foreman'
  gem 'pg'
  gem 'dm-postgres-adapter'
  gem 'capistrano'
end

# If you plan on deploying to
# Heroku, uncomment this group

# group :production do
#   gem 'pg'
#   gem 'dm-postgres-adapter'
# end

group :test do
  gem 'minitest', '~>2.6.0', :require => 'minitest/autorun'
  gem 'rack-test', :require => 'rack/test'
  gem 'factory_girl'
  gem 'database_cleaner'
end
