require 'rake/testtask'
require 'dm-migrations'
require 'open-uri'
require 'fileutils'

# Build
namespace :build do

  desc "Optimize CSS Files"
  task :css do
    puts "Compiling and minifying .sass files in app/assets/styles/"
    system 'compass compile'
  end

  desc "Optimize JS Files"
  task :js do
    puts "Compiling and minifying .sass files in app/assets/styles/"
    system 'browserify'
  end

end

# Database
namespace :db do

  task :migrate do
    require './app'
    DataMapper.auto_migrate!
  end

  task :upgrade do
    require './app'
    DataMapper.auto_upgrade!
  end

end

# Test
namespace :spec do

  task :files do
    Rake::TestTask.new do |t|
      t.libs.push("./")
      t.test_files = FileList['test/*.rb']
      t.verbose = true
    ends
  end

  task :routes do
    puts `grep '^[get|post|put|delete].*do$' routes/*.rb | sed 's/ do$//'`
  end

end
