source 'http://rubygems.org'

group :development do
    gem 'rake'
    gem 'compass', '~>0.12.alpha'
    gem 'sass', '~>3.1'
    gem 'haml', '~>3.1'
    gem 'uglifier'
end

# Use Capistrano for deployment
# gem 'capistrano', group: :development
